name: wgrib2-cygwin-compile

# used on push for testing / development
on:
  push:

# on:
#   pull_request:
#     # debug: remove the dev,putting build action on non existent branches for debug
#     branches: ['master', 'main']
#     types: ['opened', 'reopened']
#     paths-ignore:
#       - .gitignore
#       - LICENSE
#       - README.md
#       - code_of_conduct.md
      
jobs:
  # This workflow contains a single job called "build"
  buildjob:
    defaults:
      run:
        shell: bash

    name: 'Compile Wgrig2'
    # The type of runner that the job will run on
    runs-on: windows-2019
    env:
      CC: gcc
      FC: gfortran
      
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      id: checkout
      with:
        fetch-depth: 0

    - name: Get Cygwin
      id: buildSMKImage
      run: |
        powershell .\cygwin-conf.ps1

    - name: Compile wgrib2
      id: buildSMKImage
      shell: powershell
      run: |
        & .\cygdir\bin\bash.exe -c build-wgrib2.sh

& $cygdirbin\bash.exe
    - name: deploying dev
      #uses: ./comp-actions/smk-deploy
      uses: bcgov/smk-actions/smk-deploy@V1
      id: deploySMKContainer
      with:
        OPENSHIFT_SERVER_URL: ${{ secrets.OPENSHIFT_SERVER_URL }}
        OPENSHIFT_TOKEN_DEV: ${{ secrets.OPENSHIFT_TOKEN_DEV }}
        GHCR_USER: ${{ secrets.GHCR_USER }}
        GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
        DOCKER_REGISTRY: 'docker.pkg.github.com'
        PR_REVIEWERS: '["GuyTheFlower", "NicoledeGreef"]'
        PR_MENTIONS: '["GuyTheFlower", "NicoledeGreef", "franTarkenton"]'




